CFLAGS = -O2 -Wall

TARGET_CC = m68k-atari-tos-gnu-gcc

EXAMPLE_PRG =								\
	ALERT.PRG							\
	COOKIE.TOS							\
	HELLO.TOS							\
	WINDOW.PRG							\
	XBRA.PRG

.PHONY: all
all: $(EXAMPLE_PRG)

lowercase ?= $(shell echo "$(1)" | tr '[:upper:]' '[:lower:]')

define EXAMPLE_PRG_target
$(1): $(call lowercase,$(basename $(1))).c
	$$(TARGET_CC) $$(CFLAGS) -o $$@ $$^
endef

$(foreach e,$(EXAMPLE_PRG), $(eval $(call EXAMPLE_PRG_target,$(e))))

.PHONY: clean
clean:
	$(RM) $(EXAMPLE_PRG)
