#!/bin/bash

set -e
set -o pipefail

gen_ld()
{
	echo '#!/bin/bash

set -e
set -o pipefail
shopt -s nocasematch

tos_prg()
{
	[[ "$1" =~ \.(APP|GEM|GTP|PRG|TOS|TTP)$ ]]
}

args=("$@")
for (( i=1; i<$#; i++ ))
do
	# Match -o FILE.APP, -o FILE.PRG, etc.
	if [[ ${args[(( i-1 ))]} = -o ]] && tos_prg ${args[i]}
	then
		out=${args[$i]}
		elf="$out".elf
		args[$i]="$elf"
		args+=('"$TOSLIBC_PROGRAM_BASIC_LDFLAGS"')
		args+=(--script="'"$ldscriptdir"'"/prg.ld)
	fi
done

cmd()
{
	[ "x$V" != x1 ] || echo "$@"
	"$@"
}

if [[ x"$elf" != x ]]
then
	cmd "'"$TARGET_LD"'" "${args[@]}"
	cmd "'"$binutilsbindir/$target-toslink"'" -o "$out" "$elf"
	rm "$elf"
else
	cmd "'"$TARGET_LD"'" "$@"
fi'
}

if [ $# = 1 ]
then
	gen_ld >"$1".tmp
	chmod a+x "$1".tmp
	mv "$1".tmp "$1"
else
	gen_ld
fi
