#!/bin/bash

set -e
set -o pipefail

gen_ld()
{
	echo '#!/bin/bash

set -e
set -o pipefail

args=("$@")
for (( i=1; i<$#; i++ ))
do
	if [ ${args[(( i-1 ))]} = -o ]
	then
		out=${args[$i]}
		elf="$out".elf
		args[$i]="$elf"
	fi
done

"'"$TARGET_LD"'" "${args[@]}" -L"'"$libdir"'" -lc \
	'"$TOSLIBC_PROGRAM_BASIC_LDFLAGS"' \
	--script="'"$ldscriptdir"'"/prg.ld
"'"$bindir/$target-toslink"'" -o "$out" "$elf"'
}

if [ $# = 1 ]
then
	gen_ld >"$1".tmp
	chmod a+x "$1".tmp
	mv "$1".tmp "$1"
else
	gen_ld
fi
