#!/bin/bash

set -e
set -o pipefail

gen_cc()
{
	echo '#!/bin/bash

set -e
set -o pipefail
shopt -s nocasematch

tos_prg()
{
	[[ "$1" =~ \.(APP|GEM|GTP|PRG|TOS|TTP)$ ]]
}

args=("$@")
args+=(-isystem)
args+=("'"$includedir"'")
args+=('"$TOSLIBC_PROGRAM_BASIC_CFLAGS"')

for (( i=1; i<$#; i++ ))
do
	# Match -o FILE.APP, -o FILE.PRG, etc. for implicit linking
	if [[ ${args[(( i-1 ))]} = -o ]] && tos_prg ${args[i]}
	then
		out=${args[$i]}
		obj="$out".o
		args[$i]="$obj"
		args+=(-c)
	fi
done

cmd()
{
	[ "x$V" != x1 ] || echo "$@"
	"$@"
}

if [[ x"$obj" != x ]]
then
	cmd "'"$TARGET_CC"'" "${args[@]}"
	cmd "'"$binutilsbindir/$target-ld"'" -o "$out" "$obj"
	rm "$obj"
else
	cmd "'"$TARGET_CC"'" "${args[@]}"
fi'
}

if [ $# = 1 ]
then
	gen_cc >"$1".tmp
	chmod a+x "$1".tmp
	mv "$1".tmp "$1"
else
	gen_cc
fi
