#!/bin/bash

set -e
set -o pipefail

gen_cc()
{
	echo '#!/bin/bash

exec "'"$TARGET_CC"'" -isystem "'"$includedir"'" '"$TOSLIBC_PROGRAM_BASIC_CFLAGS"' "$@"'
}

if [ $# = 1 ]
then
	gen_cc >"$1".tmp
	chmod a+x "$1".tmp
	mv "$1".tmp "$1"
else
	gen_cc
fi
