name: Compile TOS/libc

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ghcr.io/frno7/gentoo-m68k:main
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Archive tag
        run: |
          echo "ARCHIVE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Compile and install TOS/libc with Linux
        env:
          TARGET_COMPILE: m68k-elf-
        run: |
          JOBS="$(getconf _NPROCESSORS_ONLN)"
          # Avoid fatal: unsafe repository (directory is owned by someone else)
          # Confer https://github.com/actions/checkout/issues/760
          git config --global --add safe.directory "$PWD"
          make -j"$JOBS" V=1 S=1
          make -j"$JOBS" V=1 S=1 install
          ls -lR ~/.local/usr/m68k-atari-tos-gnu
          export PATH=~/.local/usr/m68k-atari-tos-gnu/bin:"$PATH"
          (cd ~/.local/usr/m68k-atari-tos-gnu/share/toslibc/example && make clean && make)
          mkdir local && cp -ra ~/.local/usr/m68k-atari-tos-gnu/share/toslibc/example local

      - name: Publish examples and test suite
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: "example-test-${{ env.ARCHIVE_TAG }}"
          if-no-files-found: error
          compression-level: 9
          path: |
            example/*.PRG
            example/*.TOS
            example/*.SNDH
            local/example/*.PRG
            local/example/*.TOS
            local/example/*.SNDH
            test/SUITE.TOS
            test/test.txt

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update brew with gcc and m68k-elf-gcc
        run: |
          brew update
          brew install gcc m68k-elf-gcc

      - name: Compile and install TOS/libc with Mac OS
        env:
          TARGET_COMPILE: m68k-elf-
        run: |
          brew_prefix="${HOMEBREW_PREFIX:-$(brew --prefix)}"
          brew_gcc="$(find -L "$brew_prefix/bin" -name 'gcc-[0-9]*' 2>/dev/null | sort -Vr | head -n1)"
          echo "$brew_gcc $($brew_gcc --version | sed -n 1p)"
          JOBS="$(getconf _NPROCESSORS_ONLN)"
          # Avoid fatal: unsafe repository (directory is owned by someone else)
          # Confer https://github.com/actions/checkout/issues/760
          git config --global --add safe.directory "*"
          make -j"$JOBS" V=1 CC="$brew_gcc"
          make -j"$JOBS" V=1 CC="$brew_gcc" install
          ls -lR ~/.local/usr/m68k-atari-tos-gnu
          export PATH=~/.local/usr/m68k-atari-tos-gnu/bin:"$PATH"
          (cd ~/.local/usr/m68k-atari-tos-gnu/share/toslibc/example && make clean && make)
