name: Compile TOS/libc

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/frno7/gentoo-m68k:main
    steps:
      - uses: actions/checkout@v3

      - name: Archive tag
        run: |
          echo "ARCHIVE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Compile example archive
        env:
          TARGET_COMPILE: m68k-elf-
        run: |
          JOBS="$(getconf _NPROCESSORS_ONLN)"
          make -j"$JOBS" V=1 S=1

      - name: Publish examples
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: "example-${{ env.ARCHIVE_TAG }}"
          path: |
            example/*.PRG
            example/*.TOS
